port: 4222
http: 8222
server_name: crush-joint

authorization {
  token: "ymm_rpc_2026"
}

jetstream {
  store_dir: "/home/junknet/Desktop/_cli_bases/crush/acceptance/artifacts/relay_mobile_joint/jetstream"
}

websocket {
  port: 9091
  no_tls: true
}
