[program:crush-server]
command=/home/junknet/Desktop/_cli_bases/crush/scripts/start_server.sh
directory=/home/junknet/Desktop/_cli_bases/crush
autostart=true
autorestart=true
stderr_logfile=/var/log/crush_err.log
stdout_logfile=/var/log/crush_out.log
user=junknet
environment=PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin",HOME="/home/junknet"
